### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by ghost** [skepticfx/arpjs#11]
```
$ npm install arpjs -g

> typechecker@2.0.8 preinstall C:\Users\inf3rno\AppData\Roaming\npm\node_modules\arpjs\node_modules\typechecker
> node ./cyclic.js



> pcap@2.0.0 install C:\Users\inf3rno\AppData\Roaming\npm\node_modules\arpjs\node_modules\pcap
> node-gyp rebuild


C:\Users\inf3rno\AppData\Roaming\npm\node_modules\arpjs\node_modules\pcap>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  pcap_binding.cc
  pcap_session.cc
  win_delay_load_hook.cc
..\pcap_binding.cc(2): fatal error C1083: Cannot open include file: 'pcap/pcap.h': No such file or directory [C:\Users\inf3rno\AppData\Roaming\npm\node_modules\arpjs\node_modules\pcap\build\pcap_binding.vcxproj]
..\pcap_session.cc(2): fatal error C1083: Cannot open include file: 'pcap/pcap.h': No such file or directory [C:\Users\inf3rno\AppData\Roaming\npm\node_modules\arpjs\node_modules\pcap\build\pcap_binding.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:197:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\inf3rno\AppData\Roaming\npm\node_modules\arpjs\node_modules\pcap
gyp ERR! node -v v8.1.2
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pcap@2.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pcap@2.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\inf3rno\AppData\Roaming\npm-cache\_logs\2017-06-20T16_02_40_905Z-debug.log


```

**Comment by ghost** [comment]
Ohh I see this is a pcap error.

**Comment by ghost** [comment]
The pcap does not seem to be maintained any longer. https://github.com/node-pcap/node_pcap
Any idea how to fix this? Can't you use another dependency instead, this appears to be a complete mess, and it does not work on new node versions. Is there any alternative way (with nodejs) to capture ARP requests coming from the router?

**Comment by roccomuso** [comment]
Have you read our README first?
First of all `arpjs` has never been tested on Windows.

I'm not sure the issue is strictly related to `node_pcap`.
Do you have libpcap for windows installed?

**Comment by ghost** [comment]
I installed node_gyp and this: https://www.winpcap.org/ . Is there a way to test somehow from CLI (git bash) whether this is really working the same way as the Linux version?

note:
Many ppl use pcap on Windows according to the node_pcap issues, so in theory it works. e.g. https://github.com/node-pcap/node_pcap/issues/177
