### ISSUE TITLE
Module version mismatch. Expected 46, got 48.

### ISSUE THREAD

**Issue by roccomuso** [skepticfx/arpjs#7]
I'm having this error on Node v.4.4.7:

```
module.js:434
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: Module version mismatch. Expected 46, got 48.
    at Error (native)
    at Object.Module._extensions..node (module.js:434:18)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/user/Desktop/PROVE/pcap-test/node_modules/pcap/pcap.js:3:21)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
```

**Comment by roccomuso** [comment]
Seems that installing with `sudo` or `--unsafe-perm` gives this kind of errors.

**Comment by skepticfx** [comment]
Seems like node_pcap is breaking in latest Node. I'll fix that first. I looked at your issue in node_pcap as well. https://github.com/mranney/node_pcap/issues/220

**Comment by roccomuso** [comment]
@skepticfx Installing it without root permission have worked.
